// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/zs368/gin-example"
	"github.com/zs368/gin-example/pkg/database"
	"github.com/zs368/gin-example/pkg/log"
	"github.com/zs368/gin-example/pkg/trace"
)

// Injectors from wire.go:

func initApp() (*gin_example.App, error) {
	logger, err := log.CustomLogger()
	if err != nil {
		return nil, err
	}
	closer, err := trace.InitGlobalTracer()
	if err != nil {
		return nil, err
	}
	db, err := database.SetDB()
	if err != nil {
		return nil, err
	}
	app := &gin_example.App{
		Log:          logger,
		TracerCloser: closer,
		DB:           db,
	}
	return app, nil
}
