// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/zs368/gin-example"
	"github.com/zs368/gin-example/internal/conf"
	"github.com/zs368/gin-example/internal/server"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func initApp(http *conf.HTTP, data *conf.Data, logger *zap.Logger) (*example.App, func(), error) {
	httpServer := server.NewHTTPServer(http, logger)
	app := newApp(logger, httpServer)
	return app, func() {
	}, nil
}
