// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/zag07/gin-example/internal/data/ent/article"
	"github.com/zag07/gin-example/internal/data/ent/comment"
	"github.com/zag07/gin-example/internal/data/ent/schema"
	"github.com/zag07/gin-example/internal/data/ent/tag"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	articleFields := schema.Article{}.Fields()
	_ = articleFields
	// articleDescTitle is the schema descriptor for title field.
	articleDescTitle := articleFields[1].Descriptor()
	// article.DefaultTitle holds the default value on creation for the title field.
	article.DefaultTitle = articleDescTitle.Default.(string)
	// articleDescDesc is the schema descriptor for desc field.
	articleDescDesc := articleFields[2].Descriptor()
	// article.DefaultDesc holds the default value on creation for the desc field.
	article.DefaultDesc = articleDescDesc.Default.(string)
	// articleDescCoverImageURL is the schema descriptor for cover_image_url field.
	articleDescCoverImageURL := articleFields[3].Descriptor()
	// article.DefaultCoverImageURL holds the default value on creation for the cover_image_url field.
	article.DefaultCoverImageURL = articleDescCoverImageURL.Default.(string)
	// articleDescContent is the schema descriptor for content field.
	articleDescContent := articleFields[4].Descriptor()
	// article.DefaultContent holds the default value on creation for the content field.
	article.DefaultContent = articleDescContent.Default.(string)
	// articleDescStatus is the schema descriptor for status field.
	articleDescStatus := articleFields[5].Descriptor()
	// article.DefaultStatus holds the default value on creation for the status field.
	article.DefaultStatus = articleDescStatus.Default.(int8)
	// article.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	article.StatusValidator = articleDescStatus.Validators[0].(func(int8) error)
	// articleDescCreatedBy is the schema descriptor for created_by field.
	articleDescCreatedBy := articleFields[6].Descriptor()
	// article.DefaultCreatedBy holds the default value on creation for the created_by field.
	article.DefaultCreatedBy = articleDescCreatedBy.Default.(string)
	// articleDescUpdatedBy is the schema descriptor for updated_by field.
	articleDescUpdatedBy := articleFields[7].Descriptor()
	// article.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	article.DefaultUpdatedBy = articleDescUpdatedBy.Default.(string)
	// articleDescCreatedAt is the schema descriptor for created_at field.
	articleDescCreatedAt := articleFields[8].Descriptor()
	// article.DefaultCreatedAt holds the default value on creation for the created_at field.
	article.DefaultCreatedAt = articleDescCreatedAt.Default.(func() time.Time)
	// articleDescUpdatedAt is the schema descriptor for updated_at field.
	articleDescUpdatedAt := articleFields[9].Descriptor()
	// article.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	article.DefaultUpdatedAt = articleDescUpdatedAt.Default.(func() time.Time)
	// article.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	article.UpdateDefaultUpdatedAt = articleDescUpdatedAt.UpdateDefault.(func() time.Time)
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentFields[3].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	// commentDescUpdatedAt is the schema descriptor for updated_at field.
	commentDescUpdatedAt := commentFields[4].Descriptor()
	// comment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comment.DefaultUpdatedAt = commentDescUpdatedAt.Default.(func() time.Time)
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescStatus is the schema descriptor for status field.
	tagDescStatus := tagFields[1].Descriptor()
	// tag.DefaultStatus holds the default value on creation for the status field.
	tag.DefaultStatus = tagDescStatus.Default.(int)
	// tagDescCreatedAt is the schema descriptor for created_at field.
	tagDescCreatedAt := tagFields[4].Descriptor()
	// tag.DefaultCreatedAt holds the default value on creation for the created_at field.
	tag.DefaultCreatedAt = tagDescCreatedAt.Default.(func() time.Time)
	// tagDescUpdatedAt is the schema descriptor for updated_at field.
	tagDescUpdatedAt := tagFields[5].Descriptor()
	// tag.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tag.DefaultUpdatedAt = tagDescUpdatedAt.Default.(func() time.Time)
}
