app:
    name: gin-example
    port: 8080
    defaultPageSize: 30
    maxPageSize: 100
    uploadSavePath: storage/app/uploads
    uploadServerUrl: http://127.0.0.1:8080/static
    uploadImageMaxSize: 5
    uploadImageAllowExts:
        - .jpg
        - .jpeg
        - .png
    defaultContextTimeout:
    traceName: gin-example
    tracePort: 127.0.0.1:6831
    wsWriteWait:
    wsPongWait:
    wsMaxMessageSize:
    wsMessageQueue:
    wsOfflineNum:
auth:
    jwtSecret: echo
    jwtIssuer: gin-example
    jwtExpire:
mysql:
    host: 127.0.0.1
    port: 33061
    username: root
    password: root
    dbName: gin_example
    tablePrefix:
    charset: utf8mb4
    maxIdleConns:
    maxOpenConns: