trace:
    endpoint: http://127.0.0.1:6831/
server:
    http:
        addr: 0.0.0.0:8153
        timeout: 1s
    grpc:
        addr: 0.0.0.0:9523
        timeout: 1s
data:
    database:
        driver: mysql
        source: root:root@tcp(127.0.0.1:33061)/gin_example?charset=utf8mb4&parseTime=True&loc=Local
    redis:
        addr: 127.0.0.1:6379
        dial_timeout: 1s
        read_timeout: 0.4s
        write_timeout: 0.6s