http:
    name: gin-example
    port: :8080
    timeout:
        seconds: 1
    pageSize: 25
    maxPageSize: 100
    uploadSavePath: storage/app/uploads
    uploadServerUrl: http://127.0.0.1:8080/static
    uploadImageMaxSize: 5
    uploadImageAllowExts:
        - .jpg
        - .jpeg
        - .png
    traceName: gin-example
    tracePort: 127.0.0.1:6831
    wsWriteWait:
        seconds: 10
    wsPongWait:
        seconds: 60
    wsMaxMessageSize: 512
    wsMessageQueue: 1024
    wsOfflineNum: 10
    jwtSecret: echo
    jwtIssuer: gin-example
    jwtExpire:
        seconds: 7200
data:
    database:
        driver: mysql
        source: root:root@tcp(127.0.0.1:33061)/gin_example2?charset=utf8mb4&parseTime=True&loc=Local
    redis:
        addr: 127.0.0.1:6379
        dial_timeout:
            seconds: 1
        read_timeout:
            seconds: 0.4
        write_timeout:
            seconds: 0.6
